### PR TITLE
Simple variable effects

### PR DESCRIPTION
**Pull request by sushiinudesu**
I looked through Anbennar code for simple variable effects and here is what worked for me.
1. `set_variable`, `multiply_variable`, `check_variable` and `divide_variable` all are used without which/value. Not tested myself, but Anbennar uses it a lot.
2. For peace_treaties and diplomatic_actions_new they also use `set_variable` + u have `divide_variable` missing in diplomatic_actions_new 

Not sure if I did cardinality correctly, so pls check.

#### Other notes
- I found this kind of check_variable: ```check_variable = { which = FederationPoints who = FROM }```
- And this set_variable ```set_variable = { name = plumstead_expedition_var value = 0 }```

Not sure if both work thou :)

### CODE REVIEW

**Comment by 17blue17** [comment]
before we do anything I would like to know why check variable is failing in common ages reformation.   We need to fix that first 
 and the conflict between this  PR and the triggers file.  Then we can move on to changing other variable stuff.   I don't really understand variables - all I can do is try to make changes in CWtools and see if errors go away.   We need to wait for Maxice8 to have some free time.

**Comment by sushiinudesu** [comment]
Another thing I found by looking at Anbennar code - they use more things in `export_to_variable` as value. Here is the full list:
```
trigger_value:army_size
trigger_value:num_of_mercenaries
trigger_value:always
trigger_value:mercantilism
modifier:accept_vassalization_reasons
modifier:diplomatic_reputation
prestige
dominant_culture
primary_culture
religion
unrest
army_size
mil_tech
land_forcelimit
dip_tech
adm_tech
trigger_value:construction_progress
trigger_value:trade_node_value
trigger_value:ruler_age
0
trigger_value:light_ships_in_province
culture
trigger_value:heavy_ships_in_province
trigger_value:galleys_in_province
trigger_value:transports_in_province
trigger_value:development
```

**Comment by 17blue17** [comment]
I will do separate PR for your export_to_variable additions additions shortly.   I plan to do separate PR's for the items here as I want to take in small parts.  Then close this PR without merging it.   Kind of a quality control for me.  I hope Maxice8 has time to help.

**Comment by 17blue17** [comment]
OK I started working on set_variable using the kind of code from check_variable as a template and I got lost.   I don't have anything to test against so at this point I will wait for input from Maxice8 on your non enum items above.  Sorry.

**Comment by 17blue17** [comment]
I downloaded your mod and I found examples:   

            set_variable = { cons_prog = 0.5 }

            multiply_variable = { speed = 0.9 }

            divide_variable = { finalCost = 10 }

**Comment by 17blue17** [comment]
alright I am going to do a separate pull request for multiply, divide, set, subtract, and change variable.   Please let me know if any problems.  I will then look at the diplomatic actions issue above.   When we are finished I will close this PR without merging.

**Comment by 17blue17** [comment]
Alright I think I have made all the necessary changes and this PR can be closed.   Please let me know if still issues.

**Comment by 17blue17** [comment]
I am going to close this PR.  If any other issues then open a issue and I will try to fix.

**Pull request closed without merging**
