### PR TITLE
effects: add missing alias[effect:X]

### PR DESCRIPTION
**Pull request by maxice8**

### CODE REVIEW

**Comment by 17blue17** [comment]
there is a conflict that prevents merging this.  Please bring your branch up to date with master and try again.  I don't want to goof things up by making a guess on how to fix.

**Comment by maxice8** [comment]
> there is a conflict that prevents merging this. Please bring your branch up to date with master and try again. I don't want to goof things up by making a guess on how to fix.

Please do not close Pull Requests after you asking me to bring the branch up to date. A Pull request is not a static once-and-done thing, up to the point you merge it I can make changes.

The expected workflow is:

1. I post Pull Request
2. You check
2a. If the changes are wanted and are suitable for inclusion, merge it and it is done
2b. If the changes are wanted but are not suitable for inclusion at the moment, you ask for changes to be made
2c. If the changes are not wanted, you explain why and close it
3. I push a new version of the pull request that tries to address the requested changes
4. go to 2

**Comment by 17blue17** [comment]
Ok thanks for the information.  I have never closed someone elses requests before.How do I report the problem to you with out closing?  Simply by making a comment? It is strange that there are merge conflicts as I have only changed enums recently. Again thanks for the information    Sent from Mail for Windows From: maxice8Sent: Saturday, September 17, 2022 10:45 PMTo: cwtools/cwtools-eu4-configCc: 17blue17; State changeSubject: Re: [cwtools/cwtools-eu4-config] effects: add missing alias[effect:X] (PR #132) there is a conflict that prevents merging this. Please bring your branch up to date with master and try again. I don't want to goof things up by making a guess on how to fix.Please do not close Pull Requests after you asking me to bring the branch up to date. A Pull request is not a static once-and-done thing, up to the point you merge it I can make changes.The expected workflow is:I post Pull RequestYou check2a. If the changes are wanted and are suitable for inclusion, merge it and it is done2b. If the changes are wanted but are not suitable for inclusion at the moment, you ask for changes to be made2c. If the changes are not wanted, you explain why and close itI push a new version of the pull request that tries to address the requested changesgo to 2—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you modified the open/close state.Message ID: ***@***.***>

**Comment by maxice8** [comment]
You can just leave a comment, I will update the pull request and you can check again.

A conflict will arise because the file was changed in the section that the pull request changes, git does not try to smartly deal with it, it produces a conflict error and lets the user correct the conflict.

**Pull request closed without merging**
