### PR TITLE
Fixed other_overlord count

### PR DESCRIPTION
**Pull request by sushiinudesu**
Warning in subject_types when having more than one other_overlord, when it should be multiple

Screenshot (31)

### CODE REVIEW

**Comment by 17blue17** [comment]
you changed the wrong line.  You are allowing other_overlord = all to be repeated ( note the = all ).   The other_overlord = <subject_type> already is 0..inf so I am not sure what you are trying to fix.   The ## cardinality above the item controls not the one below.

**Comment by sushiinudesu** [comment]
But this change removes the warning. I think the 1 in all is the issue, cause it gets confused. The line higher is already inf, so it's not the cause for warning.

**Comment by 17blue17** [comment]
from what I can see the original file should work fine.  It allows one other_overlord = all and unlimited other_overlord = subject types.    So I don't understand what error you are trying to fix.  Please list the error or warning you are receiving.   Often cwtools gets confused and has to be completely closed and reopened.  Other times an error can be caused by something else above.   Note I have asked Maxice8 to look at all your pull requests when he has time.  He might be able to see something I don't.

**Comment by 17blue17** [comment]
I can recreate the issue but I think it is more complicated than what you think.  The code looks good and yet if I change something near the bottom all the sudden I have errors in places I did not change.  Something is wrong with the file itself in total.   The code you keep looking at should be fine.   I will keep looking and hopefully maxice8 can find something....... Strange.

**Comment by 17blue17** [comment]
cwtools is linking two items together as if they were triggers rather than text = x  and text = y  and I can't find a way to break the link.    

 `## cardinality = 0..inf
other_overlord = <subject_type>

## cardinality = 0..1
other_overlord = all`

**Comment by 17blue17** [comment]
ok Caligula says we have to use 0 to inf for both as cwtools can not work the way we want.  Worse case he thinks if someone use all more than once it will not hurt anything.  I will close this pull request and do my own to fix to make sure we are only changing what I think we need to change.    Thanks for the report.

**Comment by sushiinudesu** [comment]
> I think it actually should be this instead, as this seems to work as OR.
> ```
> ## cardinality = 0..inf 
> other_overlord = <subject_type>
> other_overlord = all
> ```

Will this not work? I understand that u want to keep all at 1, but probably EU4 shouldn't care if u type it multiple times.

**Comment by 17blue17** [comment]
Your code might work but it is not how it is supposed to be done.  They are not supposed to be combined like that.   I will have separate  with both 0 to inf.

**Pull request closed without merging**
